const messages = Object.freeze({
  en: {
    success: {
      REGISTER_SUCCESS: "Register successfully!",
      LOGIN_SUCCESS: "Login successfully!",
      CREATE_SUCCESS: "Create successfully!",
      DELETE_SUCCESS: "Delete successfully!",
      UPDATE_SUCCESS: "Update successfully!",
      GET_SUCCESS: "Get successfully!",
      LOGOUT_SUCCESS: "Logout successfully!",
      REFRESH_TOKEN_SUCCESS: "Refresh token successfully!",
      VERIFY_EMAIL_SUCCESS: "Verify email successfully!",
      FORGOT_PASSWORD_SUCCESS: "Forgot password successfully!",
      RESET_PASSWORD_SUCCESS: "Reset password successfully!",
      CHANGE_PASSWORD_SUCCESS: "Change password successfully!",
      UPDATE_PROFILE_SUCCESS: "Update profile successfully!",
      GET_PROFILE_SUCCESS: "Get profile successfully!",
      GET_LIST_SUCCESS: "Get list successfully!",
      GET_DETAIL_SUCCESS: "Get detail successfully!",
      CONNECT_DB_SUCCESS: "Connect database successfully!",
      DELETE_PRODUCT_SUCCESS: "Delete product successfully!",
    },
    error: {
      TOKEN_INVALID: "Token invalid!",
      CONNECT_DB_FAIL: "Connect database fail!",
      NOT_FOUND: "NOT FOUND",
      CREATE_FAIL: "Create fail!",
      DELETE_FAIL: "Delete fail!",
      UPDATE_FAIL: "Update fail!",
      GET_FAIL: "Get fail!",
      LOGIN_FAIL: "Login fail!",
      REGISTER_FAIL: "Register fail!",
      UNAUTHORIZED: "Unauthorized!",
      SERVER_ERROR: "Server error!",
      EMAIL_EXIST: "Email already exists!",
      USERNAME_EXIST: "Username already exists!",
      EMAIL_NOT_FOUND: "Email not found!",
      PASSWORD_NOT_MATCH: "Password not match!",
      INVALID_EMAIL: "Invalid email!",
      INVALID_PASSWORD: "Invalid password!",
      PERMISSION_DENIED: "Permission denied!",
    },
  },
  vi: {
    success: {
      REGISTER_SUCCESS: "Đăng ký thành công!",
      LOGIN_SUCCESS: "Đăng nhập thành công!",
      CREATE_SUCCESS: "Tạo mới thành công!",
      DELETE_SUCCESS: "Xóa thành công!",
      UPDATE_SUCCESS: "Cập nhật thành công!",
      GET_SUCCESS: "Lấy dữ liệu thành công!",
      LOGOUT_SUCCESS: "Đăng xuất thành công!",
      REFRESH_TOKEN_SUCCESS: "Làm mới token thành công!",
      VERIFY_EMAIL_SUCCESS: "Xác thực email thành công!",
      FORGOT_PASSWORD_SUCCESS: "Quên mật khẩu thành công!",
      RESET_PASSWORD_SUCCESS: "Đặt lại mật khẩu thành công!",
      CHANGE_PASSWORD_SUCCESS: "Đổi mật khẩu thành công!",
      UPDATE_PROFILE_SUCCESS: "Cập nhật hồ sơ thành công!",
      GET_PROFILE_SUCCESS: "Lấy hồ sơ thành công!",
      GET_LIST_SUCCESS: "Lấy danh sách thành công!",
      GET_DETAIL_SUCCESS: "Lấy chi tiết thành công!",
      CONNECT_DB_SUCCESS: "Kết nối cơ sở dữ liệu thành công!",
    },
    error: {
      TOKEN_INVALID: "Token không hợp lệ!",
      CONNECT_DB_FAIL: "Kết nối cơ sở dữ liệu thất bại!",
      NOT_FOUND: "Không tìm thấy!",
      CREATE_FAIL: "Tạo mới thất bại!",
      DELETE_FAIL: "Xóa thất bại!",
      UPDATE_FAIL: "Cập nhật thất bại!",
      GET_FAIL: "Lấy dữ liệu thất bại!",
      LOGIN_FAIL: "Đăng nhập thất bại!",
      REGISTER_FAIL: "Đăng ký thất bại!",
      UNAUTHORIZED: "Không có quyền truy cập!",
      SERVER_ERROR: "Lỗi máy chủ!",
      EMAIL_EXIST: "Email đã tồn tại!",
      USERNAME_EXIST: "Tên người dùng đã tồn tại!",
      EMAIL_NOT_FOUND: "Không tìm thấy email!",
      PASSWORD_NOT_MATCH: "Mật khẩu không khớp!",
      INVALID_EMAIL: "Email không hợp lệ!",
      INVALID_PASSWORD: "Mật khẩu không hợp lệ!",
      PERMISSION_DENIED: "Không được phép!",
    },
  },
});

export default messages;